### DISCUSSION TITLE
[Infrastructure] User Infrastructure as a Code approach

### DISCUSSION THREAD

**Discussion by alefesta** [kf5i/k3ai-core#98] [Roadmap]
The current implementation of the Infrastructure through `k3ai init` is to use a single config yaml file. We aim to transform the config file into a plugin type to make it more flexible. 
The idea is to have a structure similar to:
 ```yaml
apiVersion: k3ai.in/v1alpha1
kind: Infra
metadata:
     name: "mycluster"
     type: k3s
     baseUrl: "https://k3s.io...."
 resources:
     - linux:
         installCmd: "...."
         args: "..." 
     - windows:
     - mac:
     - wsl:
```
