### ISSUE TITLE
Handle types in the plugin spec

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai-core#11]
The current spec definition is:
```golang
type PluginSpec struct {
	Files      []string `yaml:",flow"` 
	Labels     []string `yaml:",flow"`
	PluginName string   `yaml:"plugin-name"`
	PreInstall string   `yaml:"pre-install"`
}
```

We need to define other types like:
- yaml
- bash
- helm 

it should be something like:
```golang
type PluginSpec struct {
	Yaml ---> yaml files
        Bash --> bash files
        Helm --> helm files
        
	Labels     []string `yaml:",flow"`
	PluginName string   `yaml:"plugin-name"`
	PreInstall string   `yaml:"pre-install"`
      
}

```

yaml:

```yaml
plugin-name: Argo
pre-install: ""
yaml:
  - "https://raw.githubusercontent.com/argoproj/argo/stable/manifests/namespace-install.yaml"
bash:
  - bashfile
  - bashfile2
helm:
  - helmfile1
  - helmfile2

```
