### ISSUE TITLE
Add Report installation

### ISSUE THREAD

**Issue by Gsantomaggio** [kf5i/k3ai-core#25]
We already have this feature in `k3ai`:

```ini
[K3ai]
https://docs.k3ai.in/
[plugin_kfpipelines]
pipelines UI: http://192.168.1.75
[plugin_kfp_sdk]
virtual env in: /home/gas/git/kf5i/k3ai/venv
To activate it: source venv/bin/activate
```

but the plugin provides this information. 

I'd like to have a "post-Installation" section,  where the user can put a shell script to write the report.

I report the issue we haven't decided yet how to do that.

**Comment by harsimranmaan** [comment]
I think that this has a dependency on #23 to get final installation state before printing. While a post install script would certainly give the most flexibility, I think if we could spec out an interface, it would likely be easier to write the plugins 

```yaml
post-install:
- serviceName: "pipeline-ui"
- serviceLabels: "app=kubeflow-pipeline"
```yaml

We can then wait on the named/labeled service(s) to be ready and print out their details. This would however not cover the case of installing a local sdk.

**Comment by Gsantomaggio** [comment]
That's more or less what I had in mind. 
I just would add a parameter:
```yaml
post-install:
- serviceName: "pipeline-ui"
- serviceLabels: ["app=kubeflow-pipeline"]
- command: <<<-- a shell script where we can put code like this: https://github.com/kf5i/k3ai-plugins/blob/main/plugin_kfpipelines/install#L121-L124 
```

In general a shell script to add what it is needed for the post installation
