### ISSUE TITLE
[feat] Adding capability to use a config file for init command

### ISSUE THREAD

**Issue by alfsuse** [kf5i/k3ai-core#68]
It would be great to be able to pass something like:
```BASH
k3ai-cli init --config $HOME/.k3ai/config.yaml
````
The config would have a structure similar to this:
```YAML
--- 
infra: 
#Infra for local deployment example
  local: 
    - 
      args: "--write-kubeconfig-mode 644"
      name: k3ai-demo
      type: k3s
    - 
      args: "--enable-worker"
      name: k3ai-demo-2
      type: k0s
#Infra for cloud deployment example
  cloud: 
    - 
      name: k3ai-demo
      nodeType: g2.large
      numNodes: 1
      secret: abced-12345-adsds-0987-abc
      type: civo
    - 
      key: 1234567
      name: k3ai-demo-2
      nodeType: g2.large
      secret: abced-12345-adsds-0987-abc
      type: azure
#plugins and groups are mutual exclusive still may be used in combination
  groups: 
    - list: [ 
        kubeflow-pipelines-traefik, 
        jupyter-pipelines-traefic
    ]
  plugins:  
    - list: [
        kubeflow-pipelines,
        jupyter-minimal, katib
    ]
```
`init --config` will parse the config file and deploy the clusters accordingly followed by the plugins/groups installation.
To do so we need to:
- have cloud/local deployment done with wait routine to knows:
  - When the cluster is up
  - When minimal pods are Ready
- Get Kubeconfig from the cluster and make it available to k3ai-cli
  - Create a kubeconfig dedicated under .k3ai folder (this require deploy each cluster and merge the various kubeconfig with contexts
  - set KUBECONFIG env to be used accordingly 
-  (OPTIONAL) Deploy at the same time cloud and local clusters.
